version: '3.8'

services:
  db_api:
    image: postgres
    container_name: nwe-year-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=psql
      - POSTGRES_USER=postgres
      - POSTGRES_DB=new-year-admin-db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
